name: Deploy on the cloud and test the API

on:
  push:
    branches:
      - main
    paths:
      - "**/src/main/**"
      - "**/pom.xml"
      - ".github/workflows/deployment.yml"

env:
  MAVEN_SERVER_ID: github-packages # this is the id set in pom.xml

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - PROVIDER: azure
            APP_NAME_SECRET: AZURE_FUNCTION_NAME
          - PROVIDER: gcloud
            APP_NAME_SECRET: GCLOUD_FUNCTION_NAME
            DEPLOYMENT_DIR: deployment

    env:
      APP_NAME: ${{ secrets[matrix.APP_NAME_SECRET] }}
      AGNOSTIC_FUNCTION_ADAPTER: ${{ matrix.PROVIDER }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ${{ env.MAVEN_SERVER_ID }}
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Package
        uses: axel-op/agnostic-serverless-functions-java-package-action@main
        with:
          function-name: ${{ env.APP_NAME }}
          faas-provider: ${{ matrix.PROVIDER }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Deploy on Azure
        if: ${{ matrix.PROVIDER == 'azure' }}
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.APP_NAME }}
          package: "./target/azure-functions/${{ env.APP_NAME }}"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
      - name: Authenticate on Google Cloud
        if: ${{ matrix.PROVIDER == 'gcloud' }}
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
      - name: Deploy on Google Cloud
        if: ${{ matrix.PROVIDER == 'gcloud' }}
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.APP_NAME }}
          region: ${{ secrets.GCLOUD_FUNCTION_REGION }}
          source_dir: target/${{ matrix.DEPLOYMENT_DIR }}
          entry_point: fr.axelop.agnosticserverlessfunctions.FunctionInvoker
          runtime: java11
      - name: Test
        run: |
          if [[ ${{ matrix.PROVIDER }} == "gcloud" ]]; then
            URL="${{ steps.deploy.outputs.url }}"
          else
            URL="https://${{ env.APP_NAME }}.azurewebsites.net/api/handler"
          fi
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
          if [[ "$STATUS_CODE" != 2* ]]; then
            echo "Invalid status code: $STATUS_CODE"
            exit 1
          fi
