name: Deploy on the cloud and test the API

on:
  push:
    branches:
      - main
    paths:
      - "**/src/main/**"
      - "**/pom.xml"
      - ".github/workflows/deployment.yml"

jobs:
  deploy-azure-functions:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ secrets.AZURE_FUNCTION_NAME }}
      AGNOSTIC_FUNCTION_ADAPTER: azure

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Package
        run: |
          SETTINGS=${GITHUB_WORKSPACE}/settings.xml
          echo '${{ secrets.SETTINGS_XML }}' > $SETTINGS
          mvn --settings=${SETTINGS} --batch-mode \
            -DappName=${APP_NAME} \
            package \
            com.microsoft.azure:azure-functions-maven-plugin:package
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.APP_NAME }}
          package: "./target/azure-functions/${{ env.APP_NAME }}"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
      - name: Test
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.AZURE_FUNCTION_URL }}/api/handler)
          if [[ "${STATUS_CODE}" != 2* ]]
          then
            echo "Invalid status code: ${STATUS_CODE}"
            exit 1
          fi

  deploy-gcloud-functions:
    runs-on: ubuntu-latest

    env:
      AGNOSTIC_FUNCTION_ADAPTER: gcloud
      DEPLOYMENT_DIR: deployment

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Package
        run: |
          SETTINGS=${GITHUB_WORKSPACE}/settings.xml
          echo '${{ secrets.SETTINGS_XML }}' > $SETTINGS
          mvn --settings=${SETTINGS} --batch-mode \
            package \
            shade:shade
          JAR_FILE=$(ls target | grep '.jar$' | grep -v '^original')
          mkdir -p target/${DEPLOYMENT_DIR}
          cp target/${JAR_FILE} target/${DEPLOYMENT_DIR}/${JAR_FILE}
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ secrets.GCLOUD_FUNCTION_NAME }}
          region: ${{ secrets.GCLOUD_FUNCTION_REGION }}
          source_dir: target/${{ env.DEPLOYMENT_DIR }}
          entry_point: fr.axelop.agnosticserverlessfunctions.FunctionInvoker
          runtime: java11
      - name: Test
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ steps.deploy.outputs.url }})
          if [[ "${STATUS_CODE}" != 2* ]]
          then
            echo "Invalid status code: ${STATUS_CODE}"
            exit 1
          fi
